### ISSUE TITLE
[Feature Request] control `Show Shadow` length

### ISSUE THREAD

**Issue by arifszn** [daveearley/screenshot.rocks#48]
Great project!

It would be nice to control the `Show Shadow` setting to make it look like this:

![image](https://user-images.githubusercontent.com/45073703/188223152-a73a70c7-2f43-4825-847e-c9db74b8b513.png)

**Comment by DomizianoScarcelli** [comment]
Yes I would love that feature too, I'll try to add it ASAP

**Comment by daveearley** [comment]
Thanks for the suggestion @arifszn! I've added the ability to alter the shadow 👍
