### ISSUE TITLE
Screenshot engine not recognizing emojis

### ISSUE THREAD

**Issue by impressivewebs** [daveearley/screenshot.rocks#62]
First of all, love the tool! I use it all the time to create screenshots.

Unfortunately, it does have a few weaknesses that I hope can be fixed. One is the fact that certain characters don't seem to display properly. For example, if I screenshot this website;

https://rollupjs.org/

Here's what I get:

https://i.imgur.com/Ab3q6lS.png

Notice the emojis that are displaying as empty boxes. Another example website you can try is: https://vitejs.dev/

**Comment by daveearley** [comment]
Thanks for reporting @impressivewebs. I'll look into this 👍

**Comment by daveearley** [comment]
This should be fixed now:
<img width="962" alt="Screenshot 2023-03-31 at 20 56 29" src="https://user-images.githubusercontent.com/166798/229264537-cb1ceac8-c0dc-49d8-abec-e38e5e4f68f9.png">
