### ISSUE TITLE
Error "Something has gone wrong. Please check your URL is valid and try again."

### ISSUE THREAD

**Issue by zcraber** [daveearley/screenshot.rocks#71]
Getting this error while entering the URL: https://free-privacy-policy-generator.digitalmalayali.in/

![image](https://github.com/daveearley/screenshot.rocks/assets/61133303/a5f1a4a2-35fe-4c6d-8e5b-d95bb7646958)

**Comment by daveearley** [comment]
Hi @zcraber, thanks for reporting! I haven't been able to reproduce this with the provided URL. What browser are you using?

**Comment by zcraber** [comment]
> Hi @zcraber, thanks for reporting! I haven't been able to reproduce this with the provided URL. What browser are you using?

Hi, seems like the issue was resolved! I couldn't reproduce it either.
